### ISSUE TITLE
Clicking on tickbox doesn't toggle it (components/TickBox.cpp#79)

### ISSUE THREAD

**Issue by Shadow1Raven** [Shadow1Raven/SDL2-GUI#7]
This is a bug which doesn't really seem to be related to the project at all.

Normally, `bool = !bool` results in the boolean value to be toggled, but due 
to the nature of C and C++, the value can be different from just `true` and
`false`. This happens, as the value is toggled between -1 and -2, which kind
 of both evaluate to `false`.

**Comment by rinukkusu** [comment]
Because you initialize the `ticked` field only in the parameter less constructor and not in the constructor you actually use in `main.cpp`, hence it never gets initialized and can have literally every value known to mankind.
